#!/bin/sh

echo "Building project... please wait (It might take about 5 minutes the first time)"
./mvnw -q -Dmaven.test.skip=true package
if [ $? -ne 0 ]; then
    echo "===  Error building project, make sure you have a JDK and the JAVA_HOME env variable set ==="
    exit 1
fi
java -jar ./target/search-workers-0.0.1-SNAPSHOT.jar "$@"
